export const sponsors = [
    {
        name: "Kents Hill Sports Camp",
        logo: "Picture1.png",
        website: "https://www.kentshillsportscamp.com/",
        color: "#9f2532",
        logoSize: "100%",
        logoOffsetY: "-10.64%",
    },
    {
        name: "Stamford Auto Group",
        logo: "Picture2.png",
        website: "https://www.stamfordautogroup.com/",
        color: "#184d91",
        logoOffsetY: "0%",
        cardPadding: "7px"
    },
    {
        name: "Cummings & Lockwood LLC",
        logo: "Picture3.png",
        website: "https://www.cl-law.com/",
        logoSize: "100%",
        logoOffsetY: "-2.03%",
        cardPadding: "12px"
    },
    {
        name: "New York Comedy Club Stamford",
        logo: "Picture4.png",
        website: "https://stamford.newyorkcomedyclub.com/",
        color: "#f0d220",
        logoOffsetY: "-1.03%",
        cardPadding: "10px"
    },
    {
        name: "MAXX Properties",
        logo: "Picture5.png",
        website: "https://www.maxxproperties.com/",
    },
    {
        name: "Kelly Feda and Lorin Pratley - Coldwell Banker Realty",
        logo: "Picture6.png",
        website:
            "https://www.coldwellbankerhomes.com/ct/greenwich/office/greenwich-office/oid_494/agents/",
        color: "#000000",
        logoSize: "100%",
        logoOffsetY: "-4.66%",
        cardPadding: "5px"
    },
    {
        name: "GOFER Ice Cream",
        logo: "Picture7.png",
        website: "https://gofericecream.com/",
        logoSize: "100%",
        logoOffsetY: "-9.28%",
        cardPadding: "8px",
    },
    {
        name: "Woolloomooloo Shoe",
        logo: "Picture8.png",
        website: "https://www.woolloomoolooshoe.com/",
        color: "#b75038",
        logoSize: "100%",
        logoOffsetY: "-3.73%",
        cardPadding: "5px"
    },
    {
        name: "Fulton Landscape Design",
        logo: "Picture9.png",
        website: "https://fultonlandscapedesign.com/",
        logoSize: "95%",
        logoOffsetY: "-21.72%",
    },
    {
        name: "Sound & Vision Destination",
        logo: "Picture10.png",
        website: "https://soundandvisionllc.com/",
        color: "#cc2a30",
        logoSize: "100%",
        logoOffsetY: "-9.4%",
    },
    {
        name: "James R. Santaguida Sanitation",
        logo: "Picture11.svg",
        website: "https://www.santaguidasanitation.com/",
        logoSize: "95%",
        logoOffsetY: "-23.09%",
    },
    {
        name: "SLS Construction",
        logo: "Picture12.png",
        website: "https://www.instagram.com/slsgreenwich/",
        cardPadding: "7px",
        logoOffsetY: "0%",
    },
    {
        name: "ONS Orthopaedic & Neurosurgery Specialists",
        logo: "Picture13.png",
        website: "https://www.onsmd.com/",
        cardPadding: "14px",
        logoOffsetY: "-2.24%"
    },
    {
        name: "Schinto Dental",
        logo: "Picture14.png",
        website: "https://schintodental.com/",
        logoSize: "100%",
        logoOffsetY: "0%",
        cardPadding: "0px"
    },
    {
        name: "Miller Motorcars",
        logo: "Picture15.png",
        website: "https://www.millermotorcars.com/",
        logoOffsetY: "-10.69%",
    },
    {
        name: "Albano Appliance",
        logo: "Picture16.png",
        website: "https://www.albanoappliance.com/",
        logoSize: "100%",
    },
    {
        name: "Triple S Cleaning Care",
        logo: "Picture17.png",
        website: "https://www.triplesclean.com/",
    },
    {
        name: "A.P. Construction Company",
        logo: "Picture18.png",
        website: "https://apconst.com/",
        color: "#951432",
        logoOffsetY: "-11.02%",
    },
    {
        name: "Garden Catering",
        logo: "Picture19.png",
        website: "https://www.gardencatering.com/",
        logoSize: "100%",
        logoOffsetY: "0.85%",
        cardPadding: "0",
    },
    {
        name: "Chillybear",
        logo: "Picture20.png",
        website: "https://www.chillybear.com/",
    },
    {
        name: "J.P. Morgan Private Bank - Greenwich",
        logo: "Picture21.png",
        website:
            "https://privatebank.jpmorgan.com/nam/en/locations/united-states/connecticut/greenwich",
    },
    {
        name: "BermudAir Holidays",
        logo: "Picture22.png",
        website: "https://www.bermudairholidays.com/en/",
        color: "#1d7872",
        logoOffsetY: "-12.77%",
    },
    {
        name: "Shoulder Check",
        logo: "Picture23.png",
        website: "https://www.shouldercheck.org/",
        color: "#161616",
        cardPadding: "0",
        logoOffsetY: "0.85%",
    },
    {
        name:
            "Bosco's Bar & Grill, Corbo's Deli, The Clubhouse and Harbor Point Pizza",
        logo: "Picture24.png",
        website: "https://boscosgrill.com/",
        logoOffsetY: "2.01%",
        cardPadding: "9px",
    },
    {
        name: "The Hockey News",
        logo: "Picture25.png",
        website: "https://thehockeynews.com/",
        logoOffsetY: "2.01%",
        cardPadding: "9px",
    },
    {
        name: "Riverside Orthodontics",
        logo: "Picture26.png",
        website: "https://riversideortho.net/",
        logoOffsetY: "-9.03%",
    },
    {
        name: "Matterhorn Fit",
        logo: "Picture27.png",
        website: "https://www.matterhornfit.com/",
        cardPadding: "15px",
        logoOffsetY: "4.29%",
    },
    {
        name: "GM Hockey",
        logo: "Picture28.png",
        website: "https://www.instagram.com/hockeycoachru10/",
        logoSize: "76%",
        logoOffsetY: "-28.42%",
    },
    {
        name: "Blockboard",
        logo: "Picture29.png",
        website: "https://www.myblockboard.com/",
        logoOffsetY: "7.22%",
    },
    {
        name: "Langner Renovations",
        logo: "Picture30.png",
        website: "https://www.langnerllc.com/",
        logoSize: "75%",
        logoOffsetY: "-25.85%",
    },
    {
        name: "Carnegie Prep",
        logo: "Picture31.png",
        website: "https://www.carnegieprep.com/",
        color: "#223e6d",
        logoOffsetY: "-19.51%",
    },
    {
        name: "Avity Investment Management Inc.",
        logo: "Picture32.jpg",
        website: "https://avityim.com/",
        color: "#0b1f37",
        logoSize: "100%",
        logoOffsetY: "-9.02%",
    },
    {
        name: "gearUP",
        logo: "Picture33.png",
        website: "https://gearupwithus.com/",
        logoSize: "82%",
    },
    {
        name: "Rogers McCagg Architects, Planners and Interior Designers",
        logo: "Picture34.jpg",
        website: "https://rm-arch.com/",
        logoSize: "64%",
        logoAlign: "start",
        logoOffsetY: "-10%",
    },
    {
        name: "Athletic Brewing Company",
        logo: "Picture35.jpg",
        website: "https://athleticbrewing.com/",
        logoSize: "85%",
        logoAlign: "start",
        logoOffsetY: "-15%",
    },
    {
        name: "BonJo Coffee Roasters",
        logo: "Picture36.png",
        website: "https://bonjocoffeeroasters.bigcartel.com/",
        cardPadding: "0px",
        logoOffsetY: "-1.71%",
    },
    {
        name: "New Country Motor Car Group",
        logo: "Picture37.png",
        website: "https://www.newcountry.com/",
        logoSize: "95%",
        logoOffsetY: "-18.64%",
    },
];